### ISSUE TITLE
Newer Version in Moodle Plugins Database

### ISSUE THREAD

**Issue by tholudwig** [eummena/moodle-antivirus_mimeblocker#4]
Hi,

according to my moodle, there is a newer version for antivirus_mimeblocker. Unfortunately, it's just available as zip download and not in the github repo.

It would be nice, if the newest version would be available in github as well.

**Comment by azmatksa** [comment]
Dear @tholudwig, 

Thank you for raising the issue. 

It's now available on Github, please download it.

**Comment by azmatksa** [comment]
I'm closing this issue as we updated plugin on Github and Moodle community.
