### ISSUE TITLE
Cannot upload course backup files (.mbz)

### ISSUE THREAD

**Issue by bfriesenvcc** [eummena/moodle-antivirus_mimeblocker#5]
The plugin does not allow the uploading of Moodle course backup files (.mbz). I've tried to find the MIME type for this and add it, but nothing I've tried has worked.

**Comment by azmatksa** [comment]
Dear @bfriesenvcc, 

Thank you for raising the issue. 

Could you please try now the Github version of MIME Blocker and confirm us? We fixed that issue, and we'll update soon on Moodle community. 


cc: @tafkey

**Comment by bfriesenvcc** [comment]
THANK YOU! It works!!! Great support!
